### ISSUE TITLE
Learner profiles too detailed

### ISSUE THREAD

**Issue by LoreDirick** [datacamp/example-course-specs#15]
I agree that how we label courses now ("beginner", "intermediate") is not ideal, but I'm not entirely convinced by the learner profiles concept. I understand that we want to make profiles that people can relate to, but now the descriptions are too long at the very least. As a user, I would be discouraged to go through them and try to figure out how I relate to them. Also, do we want to involve marital status kind of things (eg "raising two teenage children on her own") in the description?

**Comment by gvwilson** [comment]
Moot once we shift to the profiles written by Marketing.
