### ISSUE TITLE
Step 4 not straightforward for each course type

### ISSUE THREAD

**Issue by LoreDirick** [datacamp/example-course-specs#16]
For some courses it might make sense to create some cornerstone exercises. But for other courses (eg case study courses, also: my credit risk modeling course) the entire workflow is more sequential, and exercises will change while you work through the course and data set. I'm referring to my credit risk course: this step would have been very hard for me at this stage. I could have created exercises here, but would have had to redo them, which is a time drain.

**Comment by gvwilson** [comment]
Would it make sense to combine steps 3 and 4 (summative and formative assessments) and just have instructors write a representative subset of exercises that we then put in order? cc @richierocks

**Comment by gvwilson** [comment]
Issue moved to [datacamp/authoring #10](https://github.com/datacamp/authoring/issues/10) via [**ZenHub**](https://www.zenhub.com/)
