### ISSUE TITLE
Learner profiles does not tell me as a CL what I need to know.

### ISSUE THREAD

**Issue by rasmusab** [datacamp/example-course-specs#19]
What I need to know as a CL is who the Instructor aims to make the course for. This so that both I, the instructor and then the CD are aligned on this. I feel that the Learner profiles does not help me with this. 

If I learn that

> This course will give Jasmine a basic understanding of the Unix shell so that she can help her students solve the problems they encounter using the university's systems in their statistics courses.

I still know nothing about what the course instructor assumes about the Student, and even if I cross reference [Jasmines bio](https://github.com/datacamp/learner-profiles#jasmine) it doesn't tell me much about what tools/techniques the course instructor assumes she has experience with. Also all the extra info like that she did an "MBA at Georgia State" or that she "is partially deaf" feels distracting as I don't know how to use that.

What I would like to see is a list, written in the course instructors own words, on what background the course instructor assumes for the course. Parts of it could look like this:

1. The Student knows what a file system is, and is comfortable with terms like "files", "folders", "executables" and "filenames".
2. She has used some kind of terminal-like interface before, for example in our R or Python courses.
3. She knows that both Linux and MacOs are Unix operating systems and what makes them so is because they adhere to the POSIX standard.

This is useful because now I can point to this list and say that "1 and 2 seems reasonable, but I don't think we should assume they know about POSIX standards."

**Comment by gvwilson** [comment]
Issue moved to [datacamp/authoring #12](https://github.com/datacamp/authoring/issues/12) via [**ZenHub**](https://www.zenhub.com/)
