### ISSUE TITLE
Step 5: unclear what is covered in one video in the outline

### ISSUE THREAD

**Issue by LoreDirick** [datacamp/example-course-specs#22]
What seems a bit weird to me in the listed outline is that it is unclear what is covered in one video and what is covered in another one. What I like about the current outline structure is exactly that: I tell my instructors that "main" bullets are a video, and "sub" bullets add extra details to the video and the exercises that follow if that is something the instructor already gives more details on. Also, as a CL, I don't know from this outline how many videos will be in each chapter, and if the instructor is not trying to put too much in one video.

**Comment by gvwilson** [comment]
Issue moved to [datacamp/authoring #13](https://github.com/datacamp/authoring/issues/13) via [**ZenHub**](https://www.zenhub.com/)
