### ISSUE TITLE
Writing formative assessments is like starting working on the course.

### ISSUE THREAD

**Issue by rasmusab** [datacamp/example-course-specs#24]
While I really dig that the course instructor put some example exercises in the course outline, what happened to me when I started writing the formative assessments was that I started fully working on the course. 

Like, 2-3 exercises per chapter, that's a lot of exercises to create, and to be able to create 3 exercises for each chapter you already need have a pretty good idea what the rest of the course is going to be and to know what exercises and videos go before and after. Also, in many cases a single exercise (background info, description, etc.) can be much more extensive than the example exercises given here.

I'm not saying it's bad that the course instructors create exercises, I'm just saying that we're asking them to create a substantial part of their course already as part of the course outline. One way of mitigating this would be to ask them to write down 2-3 exercise *stubs* per chapter, where a stub is more of a high level description of the task.

**Comment by gvwilson** [comment]
Issue moved to [datacamp/authoring #14](https://github.com/datacamp/authoring/issues/14) via [**ZenHub**](https://www.zenhub.com/)
