### ISSUE TITLE
Add definitive list of packages/tech at the end of specs

### ISSUE THREAD

**Issue by richierocks** [datacamp/example-course-specs#32]
In order for the CLs to write the `requirements.sh`/`requirements.R` file before handing off to the CD, it would be useful if the final step in the README was to produce a definitive list of the packages or other software required for the course.

**Comment by gvwilson** [comment]
Issue moved to [datacamp/authoring #15](https://github.com/datacamp/authoring/issues/15) via [**ZenHub**](https://www.zenhub.com/)
